spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8820
